########################################################################################

# This Makefile generated by GoMakeGen 0.3.1 using next command:
# gomakegen --metalineter --strip .

########################################################################################

.PHONY = fmt all clean deps

########################################################################################

all: gomakegen

gomakegen:
	go build -ldflags="-s -w" gomakegen.go

deps:
	go get -v pkg.re/essentialkaos/ek.v7

fmt:
	find . -name "*.go" -exec gofmt -s -w {} \;

metalinter:
	test -s $(GOPATH)/bin/gometalinter || (go get -u github.com/alecthomas/gometalinter ; $(GOPATH)/bin/gometalinter --install)
	$(GOPATH)/bin/gometalinter --deadline 30s

clean:
	rm -f gomakegen

########################################################################################

