################################################################################

# This Makefile generated by GoMakeGen 0.7.0 using next command:
# gomakegen --metalinter --strip .

################################################################################

.DEFAULT_GOAL := help
.PHONY = fmt all clean deps metalinter help

################################################################################

all: gomakegen ## Build all binaries

gomakegen: ## Build gomakegen binary
	go build -ldflags="-s -w" gomakegen.go

deps: ## Download dependencies
	git config --global http.https://pkg.re.followRedirects true
	go get -d -v pkg.re/essentialkaos/ek.v9

fmt: ## Format source code with gofmt
	find . -name "*.go" -exec gofmt -s -w {} \;

metalinter: ## Run metalinter
	test -s $(GOPATH)/bin/gometalinter || (go get -u github.com/alecthomas/gometalinter ; $(GOPATH)/bin/gometalinter --install)
	$(GOPATH)/bin/gometalinter --deadline 30s

clean: ## Clean all
	rm -f gomakegen

help: ## Show this info
	@echo -e ''
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  [33m%-12s[0m %s\n", $$1, $$2}'
	@echo -e ''

################################################################################
